services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
      - ./backend/requirements.txt:/app/requirements.txt
    env_file:
      - ./backend/.env
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/app:/usr/share/nginx/html
 
    